-- CREATE TABLE

-- 2.) STG_Job Grade
CREATE TABLE [dbo].[STG_JobGradeDailyReport]
(
	ReportDate				date,
	[GROUP]					nvarchar(100),
	Depot					nvarchar(100),
	ShipmentNumber			nvarchar(100),
	Load					nvarchar(100),
	Route					nvarchar(400),
	DMANID					nvarchar(100),
	DMANIDRef				nvarchar(100),
	DMAN					nvarchar(400),
	Helper1					nvarchar(100),
	Helper2					nvarchar(100),
	Helper3					nvarchar(100),
	Car_registration		nvarchar(100),		-- ทะเบียนรถ
	EquipmentID				nvarchar(100),
	AssetRefNo				nvarchar(100),
	EquipmentType			nvarchar(100),
	Start_Mileage			decimal(20,10),
	End_Mileage				decimal(20,10),
	PlanJGCustService		decimal(20,10),
	ActJGCustService		decimal(20,10),
	PlanOutlet				decimal(20,10),
	ActOutlet				decimal(20,10),
	GradeOutlet				decimal(20,10),
	PlanJGOutlet			decimal(20,10),
	ActJGOutlet				decimal(20,10),
	PlanCase				decimal(20,10),
	ActCase					decimal(20,10),
	GradeCase				decimal(20,10),
	PlanJGCase				decimal(20,10),
	ActJGCase				decimal(20,10),
	PlanJGTimePerf			decimal(20,10),
	ActJGTimePerf			decimal(20,10),
	GradeStartTime			decimal(20,10),
	PlanJGStartTime			decimal(20,10),
	ActJGStartTime			decimal(20,10),
	PlanUsedTime			decimal(20,10),
	ActUsedTime				decimal(20,10),
	GradeUsedTime			decimal(20,10),
	PlanJGUsedTime			decimal(20,10),
	ActJGUsedTime			decimal(20,10),
	PlanJGDistancePerf		decimal(20,10),
	ActJGDistancePerf		decimal(20,10),
	PlanDistance			decimal(20,10),
	ActDistance				decimal(20,10),
	GradeDistance			decimal(20,10),
	PlanJGDistance			decimal(20,10),
	ActJGDistance			decimal(20,10),
	PlanFuelRate			decimal(20,10),
	ActFuelRate				decimal(20,10),
	GradeFuelRate			decimal(20,10),
	PlanJGFuelRate			decimal(20,10),
	ActJGFuelRate			decimal(20,10),
	PlanProdPerf			decimal(20,10),
	ActProdPerf				decimal(20,10),
	GradeProdPerf			decimal(20,10),
	PlanJGProdPerf			decimal(20,10),
	ActJGProdPerf			decimal(20,10),
	PlanInRange				decimal(20,10),
	ActInRange				decimal(20,10),
	GradeInRange			decimal(20,10),
	PlanJGSysPerf			decimal(20,10),
	ActJGSysPerf			decimal(20,10),
	PerfSummary				decimal(20,10),
	CreatedDate				datetime,
	FinalFuelRatePlan		decimal(20,10),
	FinalFuelRateActual		decimal(20,10),
	FinalGradeFuelRate		decimal(20,10),
	Represent				nvarchar(100),				-- NO data
	MaxSpeed				decimal(20,10),
	MinSpeed				decimal(20,10),
	AvgSpeed				decimal(20,10),
	PlanStartTime			datetime,
	ActStartTime			datetime,
	OutDCTime				datetime,
	PlanEndTime				datetime,
	InDCTime				datetime,
	ActEndTime				datetime,
	UsedTimeTK				nvarchar(20),								-- Replace datatype : time
	ServiceTimeTK			nvarchar(20),								-- Replace datatype : time ONLY!
	ServiceTime				nvarchar(20),								-- Replace datatype : time
	TravelTimeTL			nvarchar(20),								-- Replace datatype : time
	IdelTimeOut				nvarchar(20),								-- Replace datatype : time ONLY!
	IdleTimeIn				nvarchar(20),								-- Replace datatype : time
	TotalIdleTime			nvarchar(20),								-- Replace datatype : time ONLY!
	StemTimeOut				nvarchar(20),								-- Replace datatype : time ONLY!
	StemTimeIn				nvarchar(20),								-- Replace datatype : time ONLY!
	StemOut_KM				decimal(20,10),
	StemIn_KM				decimal(20,10),
	ServiceTime_Exc_TotalIdleTime	nvarchar(20),								-- time,	
	UsedTime_Exc_TotalIdleTime		nvarchar(20),								-- Replace datatype : time
	SequencePlan_Sum		decimal(20,10),
	DiffSequence_Sum		decimal(20,10),
	SequenceAccuracy		decimal(20,10),
	SystemRecieveRadius		decimal(20,10),
	HoldCode				nvarchar(50),
	CancelCode				nvarchar(50),
	TelematicsTruck			nvarchar(100),
	Total_working_time_TL	nvarchar(20),				-- เวลาทำงานรวมTL				-- Replace datatype : time
	Driving_Time_TL			nvarchar(20),				-- เวลาขับขี่TL					-- Replace datatype : time
	Parking_time_TL			nvarchar(20),				-- เวลาจอดTL					-- Replace datatype : time
	Park_the_engine			nvarchar(20),				-- จอดติดเครื่อง				-- Replace datatype : time
	Distance_Tracking		decimal(20,10),				-- ระยะการเดินทาง_Tracking)
	Distance_Telematic		decimal(20,10),				-- ระยะการเดินทาง_Telematic)
	Usage_oil_Tracking		decimal(20,10),				-- ใช้น้ำมัน_Tracking)
	Usage_oil_Telematic		decimal(20,10),				-- ใช้น้ำมัน_Telematic)
	Usage_oil_rate_Tracking	decimal(20,10),				-- อัตราการใช้น้ำมัน_Tracking)
	Usage_oil_rate_Telematic decimal(20,10),				-- อัตราการใช้น้ำมัน_Telematic)
	Total					decimal(20,10),
	Safety					decimal(20,10),
	ActSafety				decimal(20,10),
	Speed					decimal(20,10),
	ActSpeed				decimal(20,10),
	WeightSpeed				decimal(20,10),
	GradeSpeed				decimal(20,10),
	Speed_Time				decimal(20,10),
	SeatBelt				decimal(20,10),
	ActSeatBelt				decimal(20,10),
	WeightSeatBelt			decimal(20,10),
	GradeSeatBelt			decimal(20,10),
	SeatBelt_Time			decimal(20,10),
	Turn					decimal(20,10),
	ActTurn					decimal(20,10),
	WeightTurn				decimal(20,10),
	GradeTurn				decimal(20,10),
	Turn_Times				decimal(20,10),
	SpeedBump				decimal(20,10),
	ActSpeedBump			decimal(20,10),
	WeightSpeedBump			decimal(20,10),
	GradeSpeedBump			decimal(20,10),
	SpeedBump_Times			decimal(20,10),
	[Break]					decimal(20,10),
	ActBreak				decimal(20,10),
	WeightBreak				decimal(20,10),
	GradeBreak				decimal(20,10),
	Break_Times				decimal(20,10),
	FreeWheeling			decimal(20,10),
	ActFreeWheeling			decimal(20,10),
	WeightFreeWheeling		decimal(20,10),
	GradeFreeWheeling		decimal(20,10),
	FreeWheeling_Times		decimal(20,10),
	Economical				decimal(20,10),
	ActEconomical			decimal(20,10),
	EngineRound				decimal(20,10),
	ActEngineRound			decimal(20,10),
	WeightEngineRound		decimal(20,10),
	GradeEngineRound		decimal(20,10),
	EngineRound_Times		decimal(20,10),
	Fuel					decimal(20,10),
	ActFuel					decimal(20,10),
	WeightFuel				decimal(20,10),
	GradeFuel				decimal(20,10),
	Fuel_Value				decimal(20,10),
	OnEngineParking			decimal(20,10),
	ActOnEngineParking		decimal(20,10),
	WeightOnEngineParking	decimal(20,10),
	GradeOnEngineParking	decimal(20,10),
	OnEngineParking_Times	decimal(20,10),
	Accelerate				decimal(20,10),
	ActAccelerate			decimal(20,10),
	WeightAccelerate		decimal(20,10),
	GradeAccelerate			decimal(20,10),
	Accelerate_Times		decimal(20,10),
	LoadDataDate			datetime
)