-- CREATE TABLE

-- 3.) STG_FTD1413_by Customer

CREATE TABLE [dbo].[STG_FTD1413_By_Customer]
(
	Month							nvarchar(100),	
	SD								nvarchar(50),	
	Delloc							nvarchar(100),	
	Delloc_Name						nvarchar(100),	
	Ship_to_party					nvarchar(100),
	Ship_to_name					nvarchar(400), 
	Customer_group					nvarchar(100),	
	Sales_Document					nvarchar(100),	
	Sales_Document_Type				nvarchar(100),	
	Delivery_Document				nvarchar(100),		
	No_of_SKU_per_DO				int			 ,
	Total_Case						decimal(20,10),					-- decimal(15,3),	
	Shipment_Number					nvarchar(100),	
	SO_Document_Date				nvarchar(20),
	Delivery_Date					nvarchar(20),
	Sales_Office					nvarchar(100),	
	Sales_offices_name				nvarchar(100),	
	Sales_Representative			nvarchar(100),	
	Group_Call_Route				nvarchar(100),	
	Call_route						nvarchar(100),	
	Loading_Priority				nvarchar(100),	
	Gross_weight					decimal(20,10),					-- decimal(15,3),	
	Shipping_Conditions				nvarchar(100),
	Driver_1						nvarchar(100),	
	Driver_name						nvarchar(400),	
	Order_type						nvarchar(100),	
	Invoice_number					nvarchar(100),	
	Item_Category					nvarchar(100),	
	Sold_to_party					nvarchar(100),	
	Sold_to_name					nvarchar(400),	
	Shipping_Point					nvarchar(100),	
	Reason_for_rejection			nvarchar(400),	
	Reason_for_rejection_Description nvarchar(400),	
	Return_DO						nvarchar(100),	
	Status_Description				nvarchar(400),	
	Settlement_Date					nvarchar(20) ,
	Delivery_Plant					nvarchar(100),	
	Report_Name						nvarchar(100),	
	SO_Document_Time				time,	
	DO_Created_by					nvarchar(100),	
	DO_Created_on					nvarchar(100),	
	DO_Created_Time					time,	
	Terms_of_Payment				nvarchar(100),	
	Update_date						nvarchar(20) ,
	Update_Time						time,	
	Update_user						nvarchar(100),	
	LoadDataDate					datetime,
	Violation_Code NVARCHAR(100),
	Violation_Description NVARCHAR(400)
)