-- CREATE VIEW

-- 1.) VW_FTD1413_By_Shipment

--CREATE VIEW [SupplyChain].[VW_FTD1413_By_Shipment] AS
--SELECT *
--FROM [dbo].[FTD1413_By_Shipment]
CREATE VIEW [SupplyChain].[VW_FTD1413_By_Shipment] AS
SELECT [Month]
      ,[Del_Date]
      ,[Shp_End_Date]
      ,[SD]
      ,[Delloc]
      ,[Delloc_Name]
      ,[Shipment_Number]
      ,[Loading_Priority]
      ,[Plan_Driver_ID]
      ,[Plan_Driver_Name]
      ,[Driver_No]
      ,[Driver_Name]
      ,[Vehicle_DSD_Group_Plan]
      ,[Vehicle_Plan]
      ,[Vehicle_DSD_Group]
      ,[Vehicle]
      ,[Cap_Cube_Plan]
      ,[Cap_Cube]
      ,[St_TimeRte_Shp_Start_Time_Plan]
      ,[Shipment_start_time]
      ,[EndTimeRte_Shp_End__Time_Plan]
      ,[Shipment_end_time]
      ,[Used_Time_Plan]
      ,[Used_Time_Actual]
      ,[No_of_helper_plan]
      ,[Total_Helper]
      ,[Distance_Plan]
      ,[Distance_Actual]
      ,[Fuel]
      ,[Rate_KM_L]
      ,[Total_Case]
      ,[Total_Case_Success]
      ,[Unsuccess_Case]
      ,[PercentPCs_Success]
      ,[PercentPCs_Unsuccess]
      ,[Cube_use_by_Shipment]
      ,[Cube_Use_Success]
      ,[Cube_Use_Unsuccess]
      ,[Unit_Case]
      ,[Unit_Case_Success]
      ,[Unit_Case_Unsuccess]
      ,[Standard_Case_Assigned]
      ,[Standard_Case_Sucess]
      ,[Standard_Case_Unsuccess]
      ,[Total_Weight]
      ,[Weight]
      ,[No_Customer_per_ship]
      ,[Total_DO_per_shipment]
      ,[Success_Del__Doc]
      ,[Unsccess_Del__Doc]
      ,[PercentDoc_Success]
      ,[Total_RGB]
      ,[Total_NRB]
      ,[Total_Can]
      ,[Total_Namthip]
      ,[Total_Still]
      ,[Total_Postmix]
      ,[Pick_up_RBG]
      ,[Other]
      ,[Truck_Occupancy]
      ,[Truck_Occupancy_Actual]
      ,[No__of_Pallet]
      ,[Bay]
      ,[D_Pallets]
      ,[Pallets_Assigned]
      ,[Full_Pallets]
      ,[Mix_Pallets]
      ,[Trip]
      ,[E1]
      ,[E2]
      ,[E3]
      ,[E4]
      ,[E5]
      ,[E9]
      ,[OTHER2]
      ,[OTHER_HB]
      ,[Start_odometer]
      ,[End_odometer]
      ,[Shipment_by]
      ,[Plan_Board_no]
      ,[Plan_Descripion]
      ,[Helper_1]
      ,[Helper_1_Name]
      ,[Helper_2]
      ,[Helper_2_Name]
      ,[Helper_3]
      ,[Helper_3_Name]
      ,[Transportation_planning_point]
      ,[Shipment_type]
      ,[Shipping_Point_Receiving_Point]
      ,[Shipment_Create_time]
      ,[Report_Version]
      ,[Max_load_weight]
      ,[Update_date]
      ,[Update_time]
      ,[Update_by]
      ,[LoadDataDate]
FROM [dbo].[FTD1413_By_Shipment]
