-- CREATE VIEW

-- 2.) VW_FTD1413_By_Customer
--CREATE VIEW [SupplyChain].[VW_FTD1413_By_Customer] AS
--SELECT *
--FROM [dbo].[FTD1413_By_Customer]

CREATE VIEW [SupplyChain].[VW_FTD1413_By_Customer] AS
SELECT [Month]
      ,[SD]
      ,[Delloc]
      ,[Delloc_Name]
      ,[Ship_to_party]
      ,[Ship_to_name]
      ,[Customer_group]
      ,[Sales_Document]
      ,[Sales_Document_Type]
      ,[Delivery_Document]
      ,[No_of_SKU_per_DO]
      ,[Total_Case]
      ,[Shipment_Number]
      ,[SO_Document_Date]
      ,[Delivery_Date]
      ,[Sales_Office]
      ,[Sales_offices_name]
      ,[Sales_Representative]
      ,[Group_Call_Route]
      ,[Call_route]
      ,[Loading_Priority]
      ,[Gross_weight]
      ,[Shipping_Conditions]
      ,[Driver_1]
      ,[Driver_name]
      ,[Order_type]
      ,[Invoice_number]
      ,[Item_Category]
      ,[Sold_to_party]
      ,[Sold_to_name]
      ,[Shipping_Point]
      ,[Reason_for_rejection]
      ,[Reason_for_rejection_Description]
      ,[Return_DO]
      ,[Status_Description]
      ,[Settlement_Date]
      ,[Delivery_Plant]
      ,[Report_Name]
      ,[SO_Document_Time]
      ,[DO_Created_by]
      ,[DO_Created_on]
      ,[DO_Created_Time]
      ,[Terms_of_Payment]
      ,[Update_date]
      ,[Update_Time]
      ,[Update_user]
      ,[LoadDataDate]
FROM [dbo].[FTD1413_By_Customer]
