CREATE VIEW [SupplyChain].[VW_FTD0002] AS
SELECT [Delivery_document]
      ,[Shipping_point]
      ,[Deliv_date_From_to]
      ,[Status]
      ,[Type_Order_PickUp]
      ,[Call_Route]
      ,[Ship_to_party]
      ,[Order_Cube]
      ,[Order_All_Case]
      ,[Shipping_Conditions]
      ,[Calling_date]
      ,[Sales_Office]
      ,[Net_Value]
      ,[Document_Date]
      ,[Time]
      ,[Gross_Weight]
	  ,[Shipment Number]
	  ,[Route Name]	
	  ,[Status Description]
	  ,[Order Type]
	  ,[Order Type Desc]
      ,[LoadDataDate]
FROM [dbo].[FTD0002]
